# Generated by Django 4.2 on 2023-07-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram1", "0003_post_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(name="post", options={"ordering": ["-id"]},),
        migrations.AlterField(
            model_name="post",
            name="photo",
            field=models.ImageField(blank=True, upload_to="instagram1/post/%Y/%m/%d"),
        ),
    ]
